# GitHub Actions Workflow responsible for cleaning up the Advent of Code Kotlin Template repository from
# the template-specific files and configurations. This workflow is supposed to be triggered automatically
# when a new template-based repository has been created.

name: Template Cleanup
on:
  push:
    branches:
      - main

jobs:

  # Run cleaning process only if workflow is triggered by the .../advent-of-code-kotlin-template repository.
  template-cleanup:
    name: Template Cleanup
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'advent-of-code-kotlin-template'
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.4.0

      # Cleanup project
      - name: Cleanup
        run: |
          export LC_CTYPE=C
          export LANG=C

          # Prepare variables
          NAME="${GITHUB_REPOSITORY##*/}"
          ACTOR=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')
          SAFE_NAME=$(echo $NAME | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          SAFE_ACTOR=$(echo $ACTOR | sed 's/[^a-zA-Z0-9]//g' | tr '[:upper:]' '[:lower:]')
          GROUP="com.github.$SAFE_ACTOR.$SAFE_NAME"

          # Replace placeholders in the template-cleanup files
          sed -i "s/%NAME%/$NAME/g" .github/template-cleanup/*
          sed -i "s/%REPOSITORY%/${GITHUB_REPOSITORY/\//\\/}/g" .github/template-cleanup/*
          sed -i "s/%GROUP%/$GROUP/g" .github/template-cleanup/*

          # Replace template package name in project files with $GROUP
          find src -type f -exec sed -i "s/com.github.hsz.aoc/$GROUP/g" {} +
          find src -type f -exec sed -i "s/Template/$NAME/g" {} +
          find src -type f -exec sed -i "s/JetBrains/$ACTOR/g" {} +

          # Move content
          mkdir -p src/main/kotlin/${GROUP//.//}
          mkdir -p src/test/kotlin/${GROUP//.//}
          cp -R .github/template-cleanup/* .
          mv src/main/kotlin/com/github/hsz/aoc/* src/main/kotlin/${GROUP//.//}/
          mv src/test/kotlin/com/github/hsz/aoc/* src/test/kotlin/${GROUP//.//}/

          # Cleanup
          rm -rf \
            .github/readme \
            .github/template-cleanup \
            .github/workflows/template-cleanup.yml
          
          find . -type d -empty -delete

      # Commit modified files
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Template cleanup"

      # Push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Create new release draft - which is not publicly visible and requires manual acceptance
      - name: Update repository topics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jq -n '{"names":["aoc-2021-in-kotlin", "kotlin", "advent-of-code", "adventofcode"]}' \
            | gh api -X PUT /repos/{owner}/{repo}/topics --input -
